server:
  port: 9090
  context-path: /solr
spring:
  data:
    solr:
      host: http://127.0.0.1:8180/solr
      repositories:
        enabled: true
      zk-host: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183

  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/searchengine?characterEncoding=utf8
    username: root
    password: root